
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO_USAC = new javax.swing.JLabel();
        Btt_Usuario = new javax.swing.JFormattedTextField();
        Btt_password = new javax.swing.JPasswordField();
        TXT_USUARIO = new javax.swing.JLabel();
        TXT_PASSWORD = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO_USAC.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        TITULO_USAC.setForeground(new java.awt.Color(255, 153, 0));
        TITULO_USAC.setText("Biblioteca USAC");
        jPanel1.add(TITULO_USAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 58, 380, 87));

        Btt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 235, 45));

        Btt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 339, 235, 45));

        TXT_USUARIO.setForeground(new java.awt.Color(255, 153, 51));
        TXT_USUARIO.setText("Usuario");
        jPanel1.add(TXT_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 178, 235, 30));

        TXT_PASSWORD.setForeground(new java.awt.Color(255, 153, 51));
        TXT_PASSWORD.setText("Contraseña");
        jPanel1.add(TXT_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 235, 33));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Desktop\\Aaron USAC\\Clases USAC Ingenieria en Sistemas\\2022\\Clases Primer Semestre 2022\\IPC 1\\LAB\\Tareas LAB\\Tarea 2\\backgroud 2.0 tarea 2.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_UsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Btt_UsuarioActionPerformed

    private void Btt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btt_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usuario = "Aaron";
        String password = "202105212";
        
        if (Btt_Usuario.getText().equals(usuario)&&Btt_password.getText().equals(password)){
            Bienvenida hola = new Bienvenida ();
            hola.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "El usuario o la contraseña son incorrectos");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Btt_Usuario;
    private javax.swing.JPasswordField Btt_password;
    private javax.swing.JLabel TITULO_USAC;
    private javax.swing.JLabel TXT_PASSWORD;
    private javax.swing.JLabel TXT_USUARIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    // End of variables declaration//GEN-END:variables
}
